name: build
'on':
  push:
    branches:
      - main
      
permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: false
    steps:
      - id: build-publish
        uses: bitovi/github-actions-react-to-github-pages@v1.2.1
        with:
         path: build # change to your build folder
